### ISSUE TITLE
Client doesn't work with the latest xstream 

### ISSUE THREAD

**Issue by rkovarik** [Silverpop/engage-api-client#29]
Client doesn't work with the latest stream (1.4.8, http://x-stream.github.io/download.html), java7
since com.silverpop.api.client.xmlapi.util.XmlApiReflectionProvider#getFieldType is never called.

com.thoughtworks.xstream.converters.ConversionException: Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor : Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
---- Debugging information ----
message            : Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
cause-exception    : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message      : Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
class              : com.silverpop.api.client.ApiResult
required-type      : com.silverpop.api.client.ApiResult
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /Envelope/Body/RESULT
class[1]            : com.silverpop.api.client.xmlapi.response.XmlApiResponseBody
class[2]            : com.silverpop.api.client.xmlapi.response.XmlApiResponseEnvelope
version            : not available
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1169)
at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1040)
at com.silverpop.api.client.xmlapi.XmlApiResponse.processRequest(XmlApiResponse.java:80)
at com.silverpop.api.client.xmlapi.XmlApiResponse.buildErrorResult(XmlApiResponse.java:70)
at com.silverpop.api.client.ApiClient.extractResult(ApiClient.java:130)
at com.silverpop.api.client.ApiClient.validateSessionAndExecuteCommand(ApiClient.java:80)
at com.silverpop.api.client.ApiClient.executeCommand(ApiClient.java:54)
at com.silverpop.api.client.ApiClient.executeCommand(ApiClient.java:49)
at com.silverpop.api.client.xmlapi.XmlApiSession.executeLogin(XmlApiSession.java:106)
at com.silverpop.api.client.xmlapi.XmlApiSession.open(XmlApiSession.java:97)
at com.silverpop.api.client.ApiClient.ensureSessionIsOpen(ApiClient.java:93)
at com.silverpop.api.client.ApiClient.validateSessionAndExecuteCommand(ApiClient.java:70)
at com.silverpop.api.client.ApiClient.executeCommand(ApiClient.java:54)
at com.silverpop.api.client.ApiClient.executeCommand(ApiClient.java:49)
at info.magnolia.silverpop.SilverpopModule.stop(SilverpopModule.java:71)
at info.magnolia.module.ModuleManagerImpl.stopModule(ModuleManagerImpl.java:410)
at info.magnolia.module.ModuleManagerImpl.stopModules(ModuleManagerImpl.java:481)
at info.magnolia.init.MagnoliaServletContextListener.contextDestroyed(MagnoliaServletContextListener.java:194)
at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4980)
at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5626)
at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1575)
at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1564)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.thoughtworks.xstream.converters.reflection.ObjectAccessException: Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.newInstance(PureJavaReflectionProvider.java:74)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.instantiateNewInstance(AbstractReflectionConverter.java:553)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:256)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
... 45 more

**Comment by larrychu-ibm** [comment]
Hi rkovarik,

Thank you for submitting the pull request. We have dedicated some internal resources to start looking at the issues. It will take some time to get to all of them. I am interested in what your interests in this project are. I see some references to Magnolia-Silverpop integration. I'd like to know how you are interested in engage api client integration and how you plan to use the product. Could you tell me a little about yourself and your organization, and what you plan to use the engage-api-client for?

Thanks,
Larry

**Comment by rkovarik** [comment]
Hi Larry,

we are working on integration between Magnolia CMS and Silverpop allowing users of both systems to benefit from connection by submitting data entered in Magnolia powered websites directly into Silverpop and by using data from Silverpop to personalise content of Magnolia powered websites.

This integration is result of collaboration between Magnolia and Silverpop. If you want to learn more about Magnolia, please have a look at our website - http://www.magnolia-cms.com <http://www.magnolia-cms.com/>

Both Magnolia and Silverpop people will be at Dmexco this week, you happen to pass by, you can get more details there.

If you have more questions do not hesitate to contact me directly.


Best regards,

Jan Haderka / CIO Magnolia International
jan.haderka@magnolia-cms.com
 <https://www.facebook.com/Magnolia>  <https://www.facebook.com/Magnolia> <https://twitter.com/rah003>  <https://twitter.com/rah003> <https://plus.google.com/+JanHaderka>  <https://plus.google.com/+JanHaderka> <https://www.youtube.com/user/MagnoliaCMSystem?sub_confirmation=1>  <https://www.youtube.com/user/MagnoliaCMSystem?sub_confirmation=1> <http://ch.linkedin.com/in/had003/>  <http://ch.linkedin.com/in/had003/> <https://www.java.net/blogs/rah003>  <https://www.java.net/blogs/rah003> <skype://jan.magnolia>

Magnolia
St Johanns-Vorstadt 38, 4056 Basel, Switzerland
Office: +41 61 228 90 00  <skype://jan.magnolia>www.magnolia-cms.com <https://www.magnolia-cms.com/>

**Comment by ChrisCurtin** [comment]
Merged into Develop. Thanks for the pull!
