### ISSUE TITLE
XStream Issue?

### ISSUE THREAD

**Issue by jasondma** [Silverpop/engage-api-client#51]
Hi,

When executing the following code, an exception is thrown trying to create the APIResult object. It seems to be related to XStream marhalling but i can't seem to get around it. Is this something people have come across? I am using the develop branch.
```
public static void main(String[] args) throws Exception {
        SpringApplication.run(SPController.class, args);
        String BASE_URL = "http://apiurl/XMLAPI"; // real url not shared
        String clientId = "id";m //real id not shared
        String clientSecret = "secret"; //real secret not shared ;)
        String refreshToken = "token"; //real token not shared
        XmlApiClientFactory clientFactory = new XmlApiClientFactory();
        OauthSession oathSession = new OauthSession(clientFactory,BASE_URL,
                clientId,clientSecret, refreshToken); //values for properly configured oath app
        GetListsCommand getListsCommand = new GetListsCommand();
        ApiClient myClient = clientFactory.createClient(oathSession);
        GetListsResult result = new GetListsResult();

        try {
            result = (GetListsResult)myClient.executeCommand(getListsCommand);

        } catch (ApiResultException ae) {
            ae.printStackTrace();
        }

    }
```

The exception is 
```
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.RuntimeException: com.thoughtworks.xstream.converters.ConversionException: Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor : Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
---- Debugging information ----
message             : Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message       : Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
class               : com.silverpop.api.client.ApiResult
required-type       : com.silverpop.api.client.ApiResult
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /Envelope/Body/RESULT
class[1]            : com.silverpop.api.client.xmlapi.response.XmlApiResponseBody
class[2]            : com.silverpop.api.client.xmlapi.response.XmlApiResponseEnvelope
version             : not available
-------------------------------
	at com.silverpop.api.client.xmlapi.XmlApiResponse.processRequest(XmlApiResponse.java:77)
	at com.silverpop.api.client.xmlapi.XmlApiResponse.buildResult(XmlApiResponse.java:52)
	at com.silverpop.api.client.ApiClient.extractResult(ApiClient.java:114)
	at com.silverpop.api.client.ApiClient.validateSessionAndExecuteCommand(ApiClient.java:70)
	at com.silverpop.api.client.ApiClient.executeCommand(ApiClient.java:43)
	at com.silverpop.api.client.ApiClient.executeCommand(ApiClient.java:38)
	at com.platformq.silverpop.SPController.main(SPController.java:104)
	... 5 more
Caused by: com.thoughtworks.xstream.converters.ConversionException: Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor : Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
---- Debugging information ----
message             : Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message       : Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
class               : com.silverpop.api.client.ApiResult
required-type       : com.silverpop.api.client.ApiResult
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /Envelope/Body/RESULT
class[1]            : com.silverpop.api.client.xmlapi.response.XmlApiResponseBody
class[2]            : com.silverpop.api.client.xmlapi.response.XmlApiResponseEnvelope
version             : not available
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1206)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1190)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1061)
	at com.silverpop.api.client.xmlapi.XmlApiResponse.processRequest(XmlApiResponse.java:75)
	... 11 more
Caused by: com.thoughtworks.xstream.converters.reflection.ObjectAccessException: Cannot construct com.silverpop.api.client.ApiResult as it does not have a no-args constructor
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.newInstance(PureJavaReflectionProvider.java:74)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.instantiateNewInstance(AbstractReflectionConverter.java:559)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 32 more
```

**Comment by ChrisCurtin** [comment]
Hi,

What version of XStreams are you using? We saw this error before 1.4.x with Java 8. Upgrading to 1.4.8 and using the changes in Develop branch solved it. 

Chris

**Comment by jasondma** [comment]
i am using jdk1.8.0_60 and XStream 1.4.8.

**Comment by ChrisCurtin** [comment]
Hi,
I pulled the latest from develop and re-ran our tests and didn't get the error (Which we do with master and 1.4.8). Can you share your pom.xml and size of the spapi-client-1.1-SNAPSHOT.jar that was created when you built the develop branch? (mine is 224KB)
Thanks
Chris

**Comment by jasondma** [comment]
here is the pom file. I am running inside of intellij so i will have to create a jar file. Thanks for the help on this...

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.3.0.RELEASE</version>
  </parent>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>2.1.2</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <modelVersion>4.0.0</modelVersion>
  <groupId>silverpop</groupId>
  <artifactId>spapi-client</artifactId>
  <packaging>pom</packaging>
  <version>1.0</version>
  <dependencies>
      <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.3.2</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>

    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-thymeleaf</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-validator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat.embed</groupId>
      <artifactId>tomcat-embed-el</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-config</artifactId>
      <version>4.0.2.RELEASE</version>
    </dependency>
      <dependency>
          <groupId>com.thoughtworks.xstream</groupId>
          <artifactId>xstream</artifactId>
          <version>1.4.8</version>
          <scope>compile</scope>
      </dependency>
      <dependency>
          <groupId>commons-httpclient</groupId>
          <artifactId>commons-httpclient</artifactId>
          <version>3.1</version>
          <scope>compile</scope>
      </dependency>
      <dependency>
          <groupId>org.apache.commons</groupId>
          <artifactId>commons-lang3</artifactId>
          <version>3.1</version>
          <scope>compile</scope>
      </dependency>

      <dependency>
          <groupId>org.testng</groupId>
          <artifactId>testng</artifactId>
          <version>6.7</version>
          <scope>test</scope>
      </dependency>
      <dependency>
          <groupId>com.beust</groupId>
          <artifactId>jcommander</artifactId>
          <version>1.0</version>
          <scope>test</scope>
      </dependency>
      <dependency>
          <groupId>org.mockito</groupId>
          <artifactId>mockito-all</artifactId>
          <version>1.9.5</version>
          <scope>test</scope>
      </dependency>
  </dependencies>

</project>
```

**Comment by ChrisCurtin** [comment]
I think the issue is you are referring to the 1.0 version in your pom:

  <groupId>silverpop</groupId>
  <artifactId>spapi-client</artifactId>
  <packaging>pom</packaging>
  <version>1.0</version>

Since we haven't deployed the 1.1 version (which is in develop) you need to build it yourself:
git checkout develop
mvn install

then update the version to 1.1-SNAPSHOT in your pom
(mvn install should push the library to your maven local repository)

**Comment by smitchelus** [comment]
@jasondma, did you get past this issue?

**Comment by jasondma** [comment]
Thanks for checking back. It was an issue with my project setup. I am using IntelliJ and had the spapi source as a subproject of my app. I had some classpath issues that were resolved when i just included the jar as dependency.

**Comment by smitchelus** [comment]
Glad to hear it is working now.
